// Generated by ESG at 2022-09-06 16:40:36. github.com/simplefelix/esg

package u

import "fmt"

type Conflict struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e Conflict) ErrorCode() interface{} {
	return "Conflict"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e Conflict) StatusCode() int {
	return 409
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e Conflict) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *Conflict) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface.
func (e Conflict) Error() string {
	return fmt.Sprintf(`%v`, e.err)
}

// ErrConflict is convenient constructor.
func ErrConflict(err interface{}) Conflict {
	return Conflict{
		err: err,
	}
}
