// Generated by ESG at 2021-09-14 14:29:15. github.com/simplefelix/esg

package u

import "fmt"

type FailedToReadRequestBody struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e FailedToReadRequestBody) ErrorCode() interface{} {
	return "FailedToReadRequestBody"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e FailedToReadRequestBody) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e FailedToReadRequestBody) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e FailedToReadRequestBody) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface
func (e FailedToReadRequestBody) Error() string {
	return fmt.Sprintf(`%v`, e.err)
}

// ErrFailedToReadRequestBody convenient constructor
func ErrFailedToReadRequestBody(err interface{}) FailedToReadRequestBody {
	return FailedToReadRequestBody{
		err: err,
	}
}
