// Generated by ESG at 2021-10-15 18:06:02. github.com/simplefelix/esg

package u

import "fmt"

type MongoWriteErr struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e MongoWriteErr) ErrorCode() interface{} {
	return "MongoWriteErr"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e MongoWriteErr) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e MongoWriteErr) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *MongoWriteErr) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface.
func (e MongoWriteErr) Error() string {
	return fmt.Sprintf(`%v`, e.err)
}

// ErrMongoWriteErr is convenient constructor.
func ErrMongoWriteErr(err interface{}) MongoWriteErr {
	return MongoWriteErr{
		err: err,
	}
}
