// Generated by ESG at 2021-10-13 16:33:12. github.com/simplefelix/esg

package u

import "fmt"

type CantStartConsumer struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e CantStartConsumer) ErrorCode() interface{} {
	return "CantStartConsumer"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e CantStartConsumer) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e CantStartConsumer) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *CantStartConsumer) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface.
func (e CantStartConsumer) Error() string {
	return fmt.Sprintf(`%v`, e.err)
}

// ErrCantStartConsumergo install github.com/SimpleFelix/esg/cmd/esg@latest is convenient constructor.
func ErrCantStartConsumer(err interface{}) CantStartConsumer {
	return CantStartConsumer{
		err: err,
	}
}
