// Package errors
// Generated by ESG. https://github.com/SimpleFelix/esg
package u

import "fmt"

type DBQueryError struct {
	_extra_ interface{}
	err     interface{}
}

func (e DBQueryError) ErrorCode() interface{} {
	return "DBQueryError"
}

func (e DBQueryError) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e DBQueryError) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *DBQueryError) SetExtra(extra interface{}) {
	e._extra_ = extra
}

func (e DBQueryError) Error() string {
	return fmt.Sprintf("%v", e.err)
}

func ErrDBQueryError(err interface{}) DBQueryError {
	return DBQueryError{
		err: err,
	}
}
