// Package errors
// Generated by ESG. https://github.com/SimpleFelix/esg
package u

import "fmt"

type DBExecutionError struct {
	_extra_ interface{}
	Err     interface{}
}

func (e DBExecutionError) ErrorCode() interface{} {
	return "DBExecutionError"
}

func (e DBExecutionError) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e DBExecutionError) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *DBExecutionError) SetExtra(extra interface{}) {
	e._extra_ = extra
}

func (e DBExecutionError) Error() string {
	return fmt.Sprintf("%v", e.Err)
}

func ErrDBExecutionError(err interface{}) DBExecutionError {
	return DBExecutionError{
		Err: err,
	}
}
