// Generated by ESG at 2021-09-14 14:31:56. github.com/simplefelix/esg

package u

import "fmt"

type FailedToUnmarshalJSON struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e FailedToUnmarshalJSON) ErrorCode() interface{} {
	return "FailedToUnmarshalJSON"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e FailedToUnmarshalJSON) StatusCode() int {
	return 400
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e FailedToUnmarshalJSON) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e FailedToUnmarshalJSON) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface
func (e FailedToUnmarshalJSON) Error() string {
	return fmt.Sprintf(`%v`, e.err)
}

// ErrFailedToUnmarshalJSON convenient constructor
func ErrFailedToUnmarshalJSON(err interface{}) FailedToUnmarshalJSON {
	return FailedToUnmarshalJSON{
		err: err,
	}
}
