// Generated by ESG at 2021-09-29 16:05:18. github.com/simplefelix/esg

package u

import "fmt"

type FailedToMarshalJSON struct {
	_extra_ interface{}
	err     interface{}
}

// ErrorCode change it as you prefer.
func (e FailedToMarshalJSON) ErrorCode() interface{} {
	return "FailedToMarshalJSON"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e FailedToMarshalJSON) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e FailedToMarshalJSON) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *FailedToMarshalJSON) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface.
func (e FailedToMarshalJSON) Error() string {
	return fmt.Sprintf(`Failed to marshall JSON to bytes. %v`, e.err)
}

// ErrFailedToMarshalJSON is convenient constructor.
func ErrFailedToMarshalJSON(err interface{}) FailedToMarshalJSON {
	return FailedToMarshalJSON{
		err: err,
	}
}
